# -*- coding: utf-8 -*-
"""finance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MvjjbrrZqn6sXf3hYv3v3oSryKOfpNlk
"""

!pip install streamlit

!pip install yfinance

import yfinance as yf
import streamlit as st

import pandas as pd

st.write("""simple stock app""")

tickerSymbol='GOOGL'
tickerData=yf.Ticker(tickerSymbol)
tickerDf=tickerData.history(period='1d',start='2010-5-31',end='2020-5-31')
st.line_chart(tickerDf.Close)
st.line_chart(tickerDf.Volume)

